name: "AI Code Reviewer Bot"
description: "Performs AI-based code review on Pull Requests using OpenAI or Gemini"

inputs:
  pr_number:
    description: "Pull Request number"
    required: true
  repository:
    description: "Repository slug (e.g., owner/repo)"
    required: true

runs:
  using: "docker"
  image: "cmd/reviewer/Dockerfile"
  entrypoint: "/app/ai-code-reviewer-bot"
  args:
    - "--config=/app/config/config.yaml"

env:
  PR_NUMBER: ${{ inputs.pr_number }}
  GITHUB_REPOSITORY: ${{ inputs.repository }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  LLM_PROVIDER: ${{ secrets.LLM_PROVIDER }}
  LLM_MODEL_NAME: ${{ secrets.LLM_MODEL_NAME }}
  API_KEY: ${{ secrets.API_KEY }}
  VCS_PROVIDER: ${{ secrets.VCS_PROVIDER }}
  GITEA_TOKEN: ${{ secrets.GITEA_TOKEN }}
  GITEA_REPOSITORY: ${{ inputs.repository }}

