name: AI Code Reviewer Bot
description: Run reviewer CLI via Docker

inputs:
  GITHUB_TOKEN:
    required: true
  API_KEY:
    required: true

runs:
  using: 'docker'
  image: ../..                      
  dockerfile: cmd/reviewer/Dockerfile
  args:
    - "--config=/app/config/config.yaml"
