name: Run Reviewer Bot (Docker)

inputs:
  GITHUB_TOKEN:
    required: true
  API_KEY:
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Build reviewer-bot Docker image
      run: docker build -t reviewer-bot -f cmd/reviewer/Dockerfile .

    - name: Run reviewer-bot
      run: |
        docker run --rm \
          -e GITHUB_TOKEN="${{ inputs.GITHUB_TOKEN }}" \
          -e PR_NUMBER="${{ env.PR_NUMBER }}" \
          -e GITHUB_REPOSITORY="${{ env.GITHUB_REPOSITORY }}" \
          -e LLM_PROVIDER="${{ env.LLM_PROVIDER }}" \
          -e LLM_MODEL_NAME="${{ env.LLM_MODEL_NAME }}" \
          -e VCS_PROVIDER="${{ env.VCS_PROVIDER }}" \
          reviewer-bot \
          --config=/app/config/config.yaml
